package com.Dao;

import com.model.User;
import com.model.UserExample;
import java.util.List;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbg.generated  Sun Apr 08 14:01:26 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbg.generated  Sun Apr 08 14:01:26 CST 2018
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbg.generated  Sun Apr 08 14:01:26 CST 2018
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbg.generated  Sun Apr 08 14:01:26 CST 2018
	 */
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbg.generated  Sun Apr 08 14:01:26 CST 2018
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_t
	 * @mbg.generated  Sun Apr 08 14:01:26 CST 2018
	 */
	int updateByPrimaryKey(User record);

}